apply plugin: 'com.android.library'
apply plugin: 'expo-module-gradle-plugin'

group = 'expo.modules.surakshaktnative'
version = '1.0.0'

android {
  namespace "expo.modules.surakshaktnative"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation "androidx.core:core-ktx:1.15.0"
}
